# docker-compose.yml
version: '3'
services:
  scala:
    build: docker/scala-sbt/
    links: 
      - database
    volumes:
      - .:/code-sample
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    ports:
      - "9000:9000"
  database:
    build: docker/postgres/
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
